[network]
bind_interface = "0.0.0.0"
bind_port = 9090

[endpoints]
[endpoints.cats]
local_path = "/cats"
remote_path = "https://cat-fact.herokuapp.com/facts"
local_method = "GET"
remote_method = "GET"
[endpoints.dogs]
local_path = "/dogs"
remote_path = "https://dog-api.kinduff.com/api/facts"
local_method = "POST"
remote_method = "GET"
